---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/signup":
    post:
      summary: Create user
      tags:
      - Session
      consumes:
      - application/json
      - application/xml
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            user:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                time_zone:
                  type: string
          required:
          - email
          - password
          - time_zone
      responses:
        '200':
          description: user created
        '422':
          description: invalid request
  "/login":
    post:
      summary: Login user
      tags:
      - Session
      consumes:
      - application/json
      - application/xml
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            user:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
          required:
          - email
          - password
          - time_zone
      responses:
        '200':
          description: login
        '401':
          description: unauthorized
  "/users/{id}":
    get:
      summary: Retrieves a user
      tags:
      - Users
      produces:
      - application/json
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        type: string
        required: true
      - name: Authorization
        in: header
        type: string
        required: true
      responses:
        '200':
          description: user found
        '401':
          description: unauthorized
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
